INSERT INTO room_type(_id, name) VALUES(1, 'Habitación Triple');
INSERT INTO room_type(_id, name) VALUES(2, 'Habitación doble (Dos camas)');
INSERT INTO room_type(_id, name) VALUES(3, 'Habitación doble');
INSERT INTO room_type(_id, name) VALUES(4, 'Habitación individual');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_type', 'EN', 'name', 'Triple Room');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_type', 'IT', 'name', 'Camera tripla');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_type', 'ES', 'name', 'Habitacion Triple');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_type', 'FR', 'name', 'Chambre triple');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_type', 'DE', 'name', 'Dreibettzimmer');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_type', 'EN', 'name', 'Double Room (Two Beds)');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_type', 'IT', 'name', 'Camera doppia (due posti letto)');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_type', 'FR', 'name', 'Chambre double (lits jumeaux)');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_type', 'ES', 'name', 'Habitación Doble (Dos Camas)');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_type', 'DE', 'name', 'Doppelzimmer (zwei Betten)');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_type', 'EN', 'name', 'Double Room');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_type', 'IT', 'name', 'Camera doppia');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_type', 'FR', 'name', 'Chambre double');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_type', 'ES', 'name', 'Habitación Doble');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_type', 'DE', 'name', 'Doppelzimmer');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_type', 'EN', 'name', 'Single Room');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_type', 'IT', 'name', 'Camera singola');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_type', 'FR', 'name', 'Chambre individuelle');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_type', 'ES', 'name', 'Habitación Simple');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_type', 'DE', 'name', 'Einzelzimmer');

INSERT INTO accommodation_category(_id, name) VALUES(1, 'Económica');
INSERT INTO accommodation_category(_id, name) VALUES(2, 'Rango medio');
INSERT INTO accommodation_category(_id, name) VALUES(3, 'Premium');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_category', 'EN', 'name', 'Economic');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_category', 'IT', 'name', 'Economia');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_category', 'FR', 'name', 'Bon marchés');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_category', 'ES', 'name', 'Economica');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_category', 'DE', 'name', 'Günstig');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_category', 'EN', 'name', 'Mid Range');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_category', 'IT', 'name', 'Medium Range');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_category', 'FR', 'name', 'Prix moyens');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_category', 'ES', 'name', 'Rango Medio');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_category', 'DE', 'name', 'Mittelklasse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_category', 'EN', 'name', 'Premium');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_category', 'IT', 'name', 'Premium');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_category', 'FR', 'name', 'Premium');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_category', 'ES', 'name', 'Premium');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_category', 'DE', 'name', 'Premium');

INSERT INTO accommodation_type(_id, name) VALUES(1, 'Penthouse');
INSERT INTO accommodation_type(_id, name) VALUES(2, 'Villa con piscina');
INSERT INTO accommodation_type(_id, name) VALUES(3, 'Apartamento');
INSERT INTO accommodation_type(_id, name) VALUES(4, 'Propiedad completa');
INSERT INTO accommodation_type(_id, name) VALUES(5, 'Casa particular');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_type', 'EN', 'name', 'Penthouse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_type', 'DE', 'name', 'Penthouse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_type', 'IT', 'name', 'Penthouse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_type', 'FR', 'name', 'Penthouse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'accommodation_type', 'ES', 'name', 'Penthouse');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_type', 'EN', 'name', 'Pool Villa');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_type', 'IT', 'name', 'Pool Villa');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_type', 'FR', 'name', 'Pool Villa');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_type', 'ES', 'name', 'Villa con Piscina');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'accommodation_type', 'DE', 'name', 'Villa mit Swimmingpool');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_type', 'EN', 'name', 'Apartment');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_type', 'IT', 'name', 'Appartamento');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_type', 'FR', 'name', 'Appartement');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_type', 'ES', 'name', 'Apartamento');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'accommodation_type', 'DE', 'name', 'Appartement');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'accommodation_type', 'EN', 'name', 'Full Property');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'accommodation_type', 'IT', 'name', 'Proprietà piena');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'accommodation_type', 'FR', 'name', 'Propriété complète');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'accommodation_type', 'ES', 'name', 'Propiedad Completa');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'accommodation_type', 'DE', 'name', 'Ganze Unterkunft');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'accommodation_type', 'EN', 'name', 'Casa particular');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'accommodation_type', 'DE', 'name', 'Privatunterkunft');

INSERT INTO room_clima(_id, name) VALUES(1, 'Aire acondicionado / Ventilador');
INSERT INTO room_clima(_id, name) VALUES(2, 'Aire acondicionado');
INSERT INTO room_clima(_id, name) VALUES(3, 'Ventilador');
INSERT INTO room_clima(_id, name) VALUES(4, 'Natural');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_clima', 'EN', 'name', 'Air Conditioning / Fan');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_clima', 'IT', 'name', 'Climate Control / Fan');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_clima', 'FR', 'name', 'Climatisation / Ventilateur');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_clima', 'ES', 'name', 'Aire Acondicionado / Ventilador');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'room_clima', 'DE', 'name', 'Klimaanlage / Ventilator');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_clima', 'EN', 'name', 'Air Conditioning');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_clima', 'IT', 'name', 'Climate Control');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_clima', 'FR', 'name', 'Climatisation');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_clima', 'ES', 'name', 'Aire Acondicionado');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'room_clima', 'DE', 'name', 'Klimaanlage');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_clima', 'EN', 'name', 'Fan');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_clima', 'IT', 'name', 'Fan');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_clima', 'FR', 'name', 'Ventilateur');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_clima', 'ES', 'name', 'Ventilador');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'room_clima', 'DE', 'name', 'Ventilator');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_clima', 'EN', 'name', 'Natural');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_clima', 'IT', 'name', 'Natural');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_clima', 'FR', 'name', 'Natural');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_clima', 'ES', 'name', 'Natural');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'room_clima', 'DE', 'name', 'Natürlich');

INSERT INTO bathroom(_id, name) VALUES(1, 'Interior privado');
INSERT INTO bathroom(_id, name) VALUES(2, 'Exterior privado');
INSERT INTO bathroom(_id, name) VALUES(3, 'Compartido');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'bathroom', 'EN', 'name', 'Private, Interior');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'bathroom', 'ES', 'name', 'Privado, Interior');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'bathroom', 'IT', 'name', 'privato, Interno');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'bathroom', 'FR', 'name', 'Intérieur , Privé');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'bathroom', 'DE', 'name', 'Eigenes Bad am Zimmer');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'bathroom', 'EN', 'name', 'Private, Exterior');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'bathroom', 'ES', 'name', 'Privado, Esterno');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'bathroom', 'IT', 'name', 'privato, Exterior');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'bathroom', 'FR', 'name', 'Privé, Extérieur');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'bathroom', 'DE', 'name', 'Gästebad');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'bathroom', 'EN', 'name', 'Shared');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'bathroom', 'ES', 'name', 'Compartido');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'bathroom', 'IT', 'name', 'Condiviso');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'bathroom', 'FR', 'name', 'Partagé');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'bathroom', 'DE', 'name', 'Gemeinsames Gästebad');

INSERT INTO room_audiovisual(_id, name) VALUES(1, 'No');
INSERT INTO room_audiovisual(_id, name) VALUES(2, 'TV');
INSERT INTO room_audiovisual(_id, name) VALUES(3, 'TV+DVD / Video');
INSERT INTO room_audiovisual(_id, name) VALUES(4, 'TV cable');

INSERT INTO reservation_status(_id, id_ref, name) VALUES(1, 0, 'Pendiente');
INSERT INTO reservation_status(_id, id_ref, name) VALUES(2, 1, 'Disponible');
INSERT INTO reservation_status(_id, id_ref, name) VALUES(3, 3, 'No disponible');
INSERT INTO reservation_status(_id, id_ref, name) VALUES(4, 4, 'Cancelada');
INSERT INTO reservation_status(_id, id_ref, name) VALUES(5, 5, 'Reservada');
INSERT INTO reservation_status(_id, id_ref, name) VALUES(6, 6, 'Vencida');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'reservation_status', 'EN', 'name', 'Pending');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'reservation_status', 'IT', 'name', 'Pending');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'reservation_status', 'FR', 'name', 'Pending');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'reservation_status', 'DE', 'name', 'Offen');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(1, 'reservation_status', 'ES', 'name', 'Pendiente');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'reservation_status', 'EN', 'name', 'Available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'reservation_status', 'IT', 'name', 'Available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'reservation_status', 'FR', 'name', 'Available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'reservation_status', 'DE', 'name', 'Verfügbar');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(2, 'reservation_status', 'ES', 'name', 'Disponible');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'reservation_status', 'EN', 'name', 'Not available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'reservation_status', 'IT', 'name', 'Not available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'reservation_status', 'FR', 'name', 'Not available');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'reservation_status', 'DE', 'name', 'Nicht verfügbar');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(3, 'reservation_status', 'ES', 'name', 'No Disponible');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'reservation_status', 'EN', 'name', 'Canceled');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'reservation_status', 'IT', 'name', 'Canceled');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'reservation_status', 'FR', 'name', 'Canceled');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'reservation_status', 'DE', 'name', 'Annulliert');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(4, 'reservation_status', 'ES', 'name', 'Cancelada');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'reservation_status', 'EN', 'name', 'Booked');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'reservation_status', 'IT', 'name', 'Booked');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'reservation_status', 'FR', 'name', 'Booked');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'reservation_status', 'DE', 'name', 'Reserviert');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(5, 'reservation_status', 'ES', 'name', 'Reservada');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(6, 'reservation_status', 'EN', 'name', 'Outdated');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(6, 'reservation_status', 'DE', 'name', 'Outdated');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(6, 'reservation_status', 'ES', 'name', 'Vencida');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(6, 'reservation_status', 'IT', 'name', 'Outdated');
INSERT INTO traslation(id_obj, type_obj, locale, field, content) VALUES(6, 'reservation_status', 'FR', 'name', 'Outdated');